### PR TITLE
Issue #16 on the log, allow @last turn count function

### PR DESCRIPTION
**Pull request by RoperNo1**
Enhancement allows users to include [@last] as a passage. If the turn count reaches the same number of passages as are in the section (excluding other turn count passages and master passages) then the text in the @last passage will run after any @n passages

### CODE REVIEW

**Comment by alexwarren** [comment]
Thanks for this!

I've made one change, moving the passage counter into compiler.js instead of having the browser need to do it every time a link is clicked.

**Comment by RoperNo1** [comment]
Hope the rework didn't cost you too much time. It makes sense to do it that way. I have to admit I was staying away from the compiler file when I realised it was all node.

Would you like me to update the documentation to include this?

**Comment by alexwarren** [comment]
No problem David. Yes if you'd like to update the documentation that would
be great!

**Comment by RoperNo1** [comment]
HI Alex, Think I may have to renege on the offer to update the documentation. I have a fair idea of what needs doing. My intention was to extend the documentation for turn count as really it is all part of the same functionality from a user's perspective. I was going to leave the existing example and text and just add further text and another example for @last. I think to do that I would need to write a Squiffy file for the new example, build the accompanying story.js file and rename them something appropriate. Then update the turncount.md with the additional text and add some javascript exactly like the preceding javascript but referencing the new files. I think that is it but I don't see I have any very viable way to test it. Presumably those Markdown files need to be converted to html and then served? If there is a way I would be glad to hear of it, because I would like to do what I said I would do.

**Comment by alexwarren** [comment]
Hi David

I can generate the files for you if you like, so all you need to worry
about is updating the documentation itself if you're still interested.

For the example, you could either add a new .squiffy file in the samples
directory, or extend the existing turncount.squiffy example.

If you do want to try to generate and test the example yourself, you would
need to:

- be using a Mac (or possibly Linux, though I've not tested this)
- install Jekyll http://jekyllrb.com/docs/installation/
- install the command-line version of Squiffy from npm
- run ./buildsamples.sh to regenerate the JavaScript files for each
.squiffy example
- run ./serve.sh to run Jekyll and view the generated documentation locally
at http://localhost:4000/

If you don't fancy doing all that, I can do it for you and test that your
example works.

Thanks!
Alex

**Comment by RoperNo1** [comment]
Hi Alex, I don't have a Mac or Linux, so think i will come unstuck with generating the files. Let's try and work around it I will submit something in the next couple of days.

David

**Pull request merged**
